### ISSUE TITLE
Uploading files to people's page

### ISSUE THREAD

**Issue by browncrowned** [APN-ComDev/apnis#171]
Not an issue, but a suggestion. How about adding a feature for admin to upload files to people's page?
The idea came up because there's a reviewer asking for an official appointment from APN for him to become proposal reviewers. So, I am thinking, to also attract them to visit their own page, what if I inform them that their official appointment can be retrieved from their APNIS page. This means admin should be able to upload files to their page. 
Could be integrated with the 'Assign a review' thing?

**Comment by hktang** [comment]
That's a nice idea! We can do this in conjunction with #156 -- after uploading, we can assign the visibility of the files.

No problem -- issue tracking should be used for any discussion :+1:
