### ISSUE TITLE
Adding nationality and gender in full proposal stage

### ISSUE THREAD

**Issue by browncrowned** [APN-ComDev/apnis#197]
Can we add **Nationality** and **Gender** under section 'Major collaborator's information'? and change **Country** as Country of residence?

The CV template sometimes are ignored and it's hard to push them to use the proponent/collaborator to use the one-page template (they would like to showcase long list of publication they end up submitting long CV in pdf file).

**Comment by hktang** [comment]
To do:

- [ ] Person controller
- [ ] FP form
- [ ] FP web/PDF view
- [ ] Excel exporter

**Comment by hktang** [comment]
Fixed by 682136f
