### ISSUE TITLE
Request to add feature for FP from a seed grant approved in previous years

### ISSUE THREAD

**Issue by cbdeguzman** [APN-ComDev/apnis#227]
One of the main outcomes of a seed grant project is to submit a full proposal for funding to APN. The proposal will be submitted for Stage 2 of the Calls process. Deadline of the full proposal is February 2019.

Perhaps there is a need to allocate a space for him where he can submit his proposal.
_Update: It seems that he did submit a summary proposal but not to CRRP (as he mentioned in his report) but to CBA._

Thank you,
Chris

**Comment by hktang** [comment]
As discussed we decided not to require the presence of a proposal when creating a project. An award can be associated with: 

A proposal from the current year
A proposal from any previous years
No proposal (custom project)

This issue will be addressed in APN-ComDev/apnis#212.
